# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-25 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=200)),
                ('idno', models.IntegerField()),
                ('location', models.DateTimeField()),
                ('gender', models.CharField(max_length=300)),
                ('maritus_status', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
