# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-21 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petero', '0004_auto_20181221_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='salary',
        ),
    ]
