# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-21 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petero', '0005_remove_jobs_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
